---
title: "Conjunto de datos estadisticos policiales 2021"
author: "Nataly Montoya Campos"
date: '2022-06-19'
output: 
  html_document:  
    theme: readable  
    toc: true  
    toc_depth: 5  
    toc_float:  
      collapsed: false  
      smooth_scroll: false   
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Presentacion

## Conjunto de datos
```{r Carga de datos}
Datos_policiales <-
  readxl::read_excel(
    "C:/Users/Fabiana/OneDrive/Documentos/Fabiana IMPORTANTE/Cursos Universidad/Procesamiento de datos Geo I/Tarea 2/Datos policiales.xls")

```

## Desarrollo de la tabla
```{r}
Datos_policiales <-
  Datos_policiales %>%
  select(Delito, Fecha, Victima, Edad, Genero, Provincia, Canton)

```


```{r Visualización de la tabla}
Datos_policiales %>%
  datatable(options = list(
    pageLength = 5,
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
  ))
```


## Gráfico de barras simples
```{r}
# 1.Cantidad de delitos por tipo de delito
ggplot2_barras_tipo_delito <-
  Datos_policiales %>%
  ggplot(aes(x = Delito)) +
  geom_bar() +
  ggtitle("Cantidad de delitos por tipo de delito") +
  xlab("Tipo de delito") +
  ylab("Cantidad") +
  theme_minimal()

ggplotly(ggplot2_barras_tipo_delito) %>% config(locale = 'es')

```


```{r}
# 2.Cantidad de delitos por mes
ggplot2_barras_tipo_delito <-
  Datos_policiales %>%
  lubridate::month(x, label = FALSE, abbr = TRUE, locale = Sys.getlocale("LC_TIME")) +
  ggplot(aes(x = Delito)) +
  geom_bar() +
  ggtitle("Cantidad de delitos por mes del año") +
  xlab("Mes del año") +
  ylab("Cantidad de delitos") +
  theme_minimal()

ggplotly(ggplot2_barras_tipo_delito) %>% config(locale = 'es')

```

# Gráfico de barras apiladas
```{r}
# 3.Tipo de delito por proporciones 
barras_apiladas_proporcion_por_delito <-
  Datos_policiales %>%
  ggplot(aes(x = Delito, fill = Genero)) +
  geom_bar(position = "fill") +
  ggtitle("Proporción de los delitos por género") +
  xlab("Tipo de delito") +
  ylab("Proporción") +
  labs(fill = "Género") +
  theme_minimal()

ggplotly(barras_apiladas_proporcion_por_delito) %>% config(locale = 'es')


```

## Gráfico de barras simples para provincias
```{r}
# 4.Cantidad de delitos para los Cantones de San José, AlajuelA, Cartago y Heredia.

barras_identity_por_cantones <-
Datos_policiales %>%
  slice_max(Provincia, n = 4) %>% 
  ggplot(aes(x = reorder(Canton,Provincia), y = Provincia)) +
  geom_bar(stat = "identity") +
  ggtitle("Cantidad de delitos para los cantones de San José, Alajuela, Cartago y Heredia") +
  xlab("Cantones") +
  ylab("Cantidad de delitos por cantón") +
  coord_flip() + 
  theme_minimal()

ggplotly(barras_identity_por_cantones) %>% config(locale = 'es')
```

